version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: detector_placas
    ports:
      - "5432:5432"
    volumes:
      - ./detector_placas.sql:/docker-entrypoint-initdb.d/detector_placas.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: